apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: experiment-controller-e2e

# Override namespace to match e2e test expectations
namespace: experimentor-system

resources:
  - ../../base

# Patch the namespace name to match e2e expectations
patches:
  - path: namespace-patch.yaml
    target:
      kind: Namespace
      name: experiment-system

images:
  - name: experimentor
    newName: example.com/experimentor
    newTag: v0.0.1

configMapGenerator:
  - name: controller-config
    behavior: merge
    literals:
      - LOG_LEVEL=info
      - METRICS_BIND_ADDRESS=:8080
      - METRICS_SECURE=false