# Default values for ping-pong.
# This is a YAML-formatted file.

replicaCount: 3

image:
  repository: httpd
  pullPolicy: IfNotPresent
  tag: "2.4"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext:
  fsGroup: 2000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: false

service:
  type: ClusterIP
  port: 80
  containerPort: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: ping-pong.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 5
  periodSeconds: 5

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}

# Ping-pong specific configuration
pingpong:
  # Environment variables for the application
  env:
    - name: APP_NAME
      value: "ping-pong"
    - name: APP_VERSION
      value: "v1.0.0"
    - name: RESPONSE_MESSAGE
      value: "pong"