{{- if not .Values.rbac.namespaceScoped }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "experiment-controller.fullname" . }}-manager-rolebinding
  labels:
    {{- include "experiment-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "experiment-controller.fullname" . }}-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "experiment-controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}