{{- if .Values.rbac.namespaceScoped }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "experiment-controller.fullname" . }}-manager-rolebinding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "experiment-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "experiment-controller.fullname" . }}-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "experiment-controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}