{{- if .Values.rbac.namespaceScoped }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "experiment-controller.fullname" . }}-manager-role
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "experiment-controller.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - rollouts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - experimentcontroller.example.com
  resources:
  - experimentdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - experimentcontroller.example.com
  resources:
  - experimentdeployments/finalizers
  verbs:
  - update
- apiGroups:
  - experimentcontroller.example.com
  resources:
  - experimentdeployments/status
  verbs:
  - get
  - patch
  - update
{{- end }}