apiVersion: apps/v1
kind: Deployment
metadata:
  name: experiment-controller
spec:
  replicas: 3
  template:
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: experiment-controller
                  app.kubernetes.io/component: controller
              topologyKey: kubernetes.io/hostname
      containers:
        - name: experiment-controller-manager
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
            requests:
              cpu: 200m
              memory: 256Mi
          args:
            - --leader-elect=true
            - --health-probe-bind-address=:8081
            - --metrics-bind-address=:8443
            - --metrics-secure=true