apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: experiment-controller-manager-rolebinding
  labels:
    app.kubernetes.io/name: experiment-controller
    app.kubernetes.io/component: controller
    app.kubernetes.io/part-of: experiment-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: experiment-controller-manager-role
subjects:
- kind: ServiceAccount
  name: experiment-controller
  namespace: experiment-system