apiVersion: apps/v1
kind: Deployment
metadata:
  name: experiment-controller
  labels:
    app.kubernetes.io/name: experiment-controller
    app.kubernetes.io/component: controller
    app.kubernetes.io/part-of: experiment-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: experiment-controller
      app.kubernetes.io/component: controller
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        app.kubernetes.io/name: experiment-controller
        app.kubernetes.io/component: controller
    spec:
      serviceAccountName: experiment-controller
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: experiment-controller-manager
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - "ALL"
            readOnlyRootFilesystem: false
            runAsNonRoot: true
          image: experimentor:v0.1.0
          imagePullPolicy: IfNotPresent
          command:
            - /manager
          args:
            - --leader-elect
            - --health-probe-bind-address=:8081
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
      terminationGracePeriodSeconds: 10