apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: experiment-controller-base

namespace: experiment-system

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - service.yaml
  - deployment.yaml
  - ../../config/crd/bases

images:
  - name: experimentor
    newTag: v0.1.0

commonLabels:
  app.kubernetes.io/name: experiment-controller
  app.kubernetes.io/component: controller
  app.kubernetes.io/part-of: experiment-controller

configMapGenerator:
  - name: controller-config
    literals:
      - WATCH_NAMESPACES=""
      - LEADER_ELECT=true
      - HEALTH_PROBE_BIND_ADDRESS=:8081