apiVersion: v1
kind: ServiceAccount
metadata:
  name: experiment-controller
  labels:
    app.kubernetes.io/name: experiment-controller
    app.kubernetes.io/component: controller
    app.kubernetes.io/part-of: experiment-controller
automountServiceAccountToken: true