# Example ExperimentDeployment for StatefulSet
apiVersion: experimentcontroller.example.com/v1alpha1
kind: ExperimentDeployment
metadata:
  name: ping-pong-statefulset-experiment
  namespace: default
spec:
  sourceRef:
    name: {{ include "ping-pong-statefulset.fullname" . }}
    namespace: default
    kind: StatefulSet
  replicas: 1
  overrideSpec:
    template:
      spec:
        containers:
        - name: ping-pong-statefulset
          env:
          - name: RESPONSE_MESSAGE
            value: "experimental-pong-stateful"
          - name: APP_VERSION
            value: "v1.0.0-experiment"
          resources:
            limits:
              cpu: 50m
              memory: 64Mi
            requests:
              cpu: 25m
              memory: 32Mi