{{- if .Values.headlessService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ping-pong-statefulset.fullname" . }}-headless
  labels:
    {{- include "ping-pong-statefulset.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ping-pong-statefulset.selectorLabels" . | nindent 4 }}
{{- end }}